tradetracker/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(max=10)])
    content = TextAreaField('Content', validators=[DataRequired(), Length(max=150)], render_kw={"class": "content"})
    submit = SubmitField('Post')

class StockForm(FlaskForm):
    ticker = StringField('Ticker', validators=[DataRequired(), Length(min=1, max=4)])
    submit = SubmitField('Search')

tradetracker/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint, send_file)
from flask_login import current_user, login_required
from tradetracker import db
from tradetracker.models import Post
from tradetracker.posts.forms import PostForm, StockForm
from bs4 import BeautifulSoup 
import requests
import re
import pandas as pd
import csv
from tradetracker.config import Config
from datetime import datetime, timedelta
posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data 
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

def fetch_earnings():
    try:
        source = requests.get('https://www.earningswhispers.com/calendar')
        soup = BeautifulSoup(source.content, 'lxml')
    except:
        flash('We\'re sorry, an error occurred with the API. Please try again later!', 'error')
        return redirect(url_for('main.home'))

    companies_html = soup.findAll('div', class_='company')
    tickers_html = soup.findAll('div', class_='ticker')
    times_html = soup.findAll('div', class_='time')
    revenue_growths_html = soup.findAll('div', class_='revgrowthprint')
    earnings_growths_html = soup.findAll('div', class_='growth')

    companies = ['Company name']
    tickers = ['Ticker']
    times = ['Time']
    revenue_growths = ['Expected Revenue Growth']
    earnings_growths = ['Expected Earnings Growth']

    for company in companies_html:
        companies.append(company.text)

    for ticker in tickers_html:
        tickers.append(ticker.text)

    for time in times_html:
        times.append(time.text)

    for revenue_growth in revenue_growths_html:
        revenue_growths.append(revenue_growth.text)

    for earning in earnings_growths_html:
        earning_script = earning.find('script', string=lambda text: text and 'showepsgrowth' in text)
        if earning_script:
            earning_text = re.search(r'showepsgrowth\("[^"]*",\s*"([^"]*)"\);', earning_script.string)
            if earning_text:
                earnings_growths.append(earning_text.group(1))

    earnings_list = list(zip(companies, tickers, times, revenue_growths, earnings_growths))

    return(earnings_list)

@posts.route('/earnings')
def earnings():
    earnings_list = fetch_earnings()
    df = pd.DataFrame(earnings_list[1:], columns=earnings_list[0])

    return render_template('earnings.html', earnings_list=earnings_list, df=df, title='Earnings')

@posts.route('/download_earnings')
def download_earnings():
    try:
        earnings_list = fetch_earnings()
        filename = 'earnings.csv' 
        with open(filename, 'w', newline='') as f:
            writer = csv.writer(f, delimiter='|')
            writer.writerows(earnings_list)
            flash('The earnings data has been downloaded and saved as a CSV file!', 'success')
        return send_file('../' + filename, as_attachment=True)
    except:
        flash(f'We\'re sorry, you can\'t download the data right now. Try again Later.', 'error')
        return redirect(url_for('posts.earnings'))

@posts.route('/news')
def news():
    key = Config.AV_KEY

    today = datetime.now()
    month_ago = today - timedelta(days=30)
    month_ago_str = month_ago.strftime("%Y%m%dT%H%M")
    try:
        url = f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&tickers=COIN,CRYPTO:BTC,FOREX:USD&time_from={month_ago_str}&sort=LATEST&apikey={key}'
        r = requests.get(url)
        data = r.json()
        articles = pd.DataFrame(data['feed'])
        articles['time_published'] = pd.to_datetime(articles['time_published']).dt.strftime('%Y-%m-%d')

        return render_template('news.html', title='Stock News', data=data, articles=articles)
    except:
        flash('We\'re sorry, an error occurred with the API. Please try again later!', 'error')
        return redirect(url_for('main.home'))
    
@posts.route('/overview', methods=['GET', 'POST'])
def overview():

    key = Config.AV_KEY
    form = StockForm()

    if form.ticker.data:
        ticker = form.ticker.data
    else:
        ticker = 'MSFT'
    try:
        url = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol={ticker}&apikey={key}'
        r = requests.get(url)
        data = r.json()
    except KeyError:
        flash('Ticker does not exists!', 'error')
        return redirect(url_for('main.home'))
    except:
        flash('We\'re sorry, an error occurred with the API. Please try again later!', 'error')
        return redirect(url_for('main.home'))
    if 'Description' in data:
        description = data['Description']
        del data['Description']
    else:
        flash('Ticker does not exists!', 'error')
        ticker = ''
        description = ''
    if form.validate_on_submit():
        ticker = form.ticker.data
        return redirect(url_for('posts.overview', ticker=ticker))

    return render_template('overview.html', title='Company Overview', data=data, form=form, description=description, ticker=ticker)

tradetracker/users/routes.py
from flask import render_template, url_for, flash, redirect, abort, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from tradetracker import db, bcrypt
from tradetracker.models import User, Post, Stock
from tradetracker.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm, PortfolioForm)
from tradetracker.users.utils import save_picture, send_reset_email
import pandas as pd
from functools import reduce
import yfinance as yf
users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.username.data is not None and len(form.username.data) < 4:
        flash('Username must have at least 5 characters', 'error')
    elif form.email.data is not None and ("@" not in form.email.data or "." not in form.email.data):
        flash('Invalid email address', 'error')
    elif form.password.data is not None and len(form.password.data) < 7:
        flash('Password must have at least 8 characters', 'error')
    elif not(form.password.data == form.confirm_password.data):
        flash('The passwords do not match', 'error')
    elif form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Account created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email and password', 'error')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=3)
    return render_template('user_posts.html',posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'error')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

@users.route('/portfolio/<string:username>', methods=['GET','POST'])
@login_required
def portfolio(username):
    if username != current_user.username:
        abort(403)
    user = User.query.filter_by(username=username).first()
    stock = Stock.query.filter_by(user_id=user.id).first()
    if stock is not None:
        stocks = Stock.query.filter_by(user_id=user.id).all()
        tickers = [stock.ticker for stock in stocks]
        amounts = [int(stock.amount) for stock in stocks]
        dates = [stock.date_posted.strftime('%Y-%m-%d') for stock in stocks]
        prices = []
        total = [] 
    else:
        tickers = []
        amounts = []
        prices = []
        total = []
        dates = []
    form = PortfolioForm()
    if form.validate_on_submit():      
        add_stock = Stock(ticker=form.ticker.data, amount=form.amount.data, user_id=user.id)
        dates.append(add_stock.date_posted)
        db.session.add(add_stock)
        db.session.commit()
        flash('The stock has been added!', 'success')
        return(redirect(url_for('users.portfolio', username=current_user.username)))
        
    ticker_to_value = {}
    for i in range(len(tickers)):     
        if tickers[i]  not in ticker_to_value:
                ticker_to_value[tickers[i]] = yf.Ticker(tickers[i])
        ticker_value = ticker_to_value[tickers[i]]
        stockinfo = ticker_value.fast_info
        last_price = stockinfo['lastPrice']
        prices.append(round(last_price,2))
        amount = amounts[i]
        total_round = round(last_price*amount,2)
        total.append(total_round)


    porftolio_stocks=list(zip(tickers, amounts, prices, total, dates))
    ticker_labels = []
    ticker_amounts = []
    pieData = []
    ticker_id = []
    total_prices = []
    if stock is not None:
        df = pd.DataFrame(porftolio_stocks[0:], columns=porftolio_stocks[0])
        same_stocks = Stock.query.filter_by(user_id=user.id).all()

        for stock in same_stocks:       
            ticker_id.append(stock.id) 
            ticker_value = ticker_to_value[stock.ticker]
            stockinfo = ticker_value.fast_info
            last_price = round(stockinfo['lastPrice'],2)
            if stock.ticker in ticker_labels:
                index = ticker_labels.index(stock.ticker)
                ticker_amounts[index] += int(stock.amount)
                total_prices[index] += round(stock.amount*last_price,2)
            else:
                ticker_labels.append(stock.ticker)
                ticker_amounts.append(int(stock.amount))
                total_prices.append(round(stock.amount*last_price,2))
                
                
        for i in range(len(ticker_amounts)):
            if ticker_amounts[i] <= 0:
                ticker_amounts.pop(i)
                ticker_labels.pop(i)
                total_prices.pop(i)
        overview = list(zip(ticker_labels, ticker_amounts, total_prices))
        df_overview = pd.DataFrame(overview[0:], columns=overview[0])

        summary = round(reduce(lambda acc, val: acc + val, total_prices),2)
                
    else: 
        overview = list(zip(ticker_labels, ticker_amounts, total_prices))
        df = pd.DataFrame(porftolio_stocks, columns=['Ticker', 'Amount', 'Price', 'Total', 'Date'])
        df_overview = pd.DataFrame(overview, columns=['Ticker', 'Amount', 'Total'])
        summary = 0

    return render_template('portfolio.html', summary=summary, df_overview=df_overview, pieData=pieData, df=df,
                            username=username, ticker_labels=ticker_labels, ticker_amounts=ticker_amounts, ticker_id=ticker_id, form=form, title='Portfolio')

@users.route("/portfolio/<int:ticker_id>/delete", methods=['POST'])
@login_required
def delete_stock(ticker_id):
    stock = Stock.query.get_or_404(ticker_id)
    if stock.user_id != current_user.id:
        abort(403)
    db.session.delete(stock)
    db.session.commit()
    flash('Your stock has been deleted!', 'success')
    return(redirect(url_for('users.portfolio', username=current_user.username)))

tradetracker/templates/about.html
{% extends "layout.html" %} 
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

tradetracker/templates/earnings.html
{% extends "layout.html" %} 
{% block content %}
    <div class="earnings-elements">
        <table class="earnings-table">
            <thead>
                <tr class="earnings-tr">
                    <th>Company name</th>
                    <th>Ticker</th>
                    <th>Time</th>
                    <th>Expected Revenue Growth</th>
                    <th>Expected Earnings Growth</th>
                </tr>
            </thead>
            <tbody>
                {% for row in df.values %}
                <tr class="earnings-tr">
                    {% for value in row %}
                    <td>{{ value }}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
            <a class="post-links" id="earnings-download" href="{{ url_for('posts.download_earnings') }}">Download Earnings </a>
    </div>
   
{% endblock %}

tradetracker/templates/home.html
{% extends "layout.html" %} 
{% block content %}
    {% for post in posts.items %}
        <article class="media">  
            <div class="media-body-posts">
                <div class="post-content">
                    <div class="article-head">
                        <div class="article-profile">
                            <img class="article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                            <a class="article-author" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username}}</a>
                        </div>
                        <small class="article-date">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                    </div>
                    <a class="article-title post-link" href="{{ url_for('posts.post', post_id=post.id ) }}"> {{ post.title }}</a>
                    <p class="article-content"> {{ post.content }}</p>
                </div>
            </div>
        </article>
    {% endfor %}
    <div class="page-container">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="page_num" id="current_page" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="page_num" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    </div>
{% endblock content %}

tradetracker/templates/layout.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{{ url_for('static', filename='bull.ico') }}" type="image/x-icon">
  <link rel="icon" href="{{ url_for('static', filename='bull.ico') }}" type="image/x-icon">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    {% if title %}
        <title>Trade Tracker - {{ title }}</title>
    {% else %}
        <title>Trade Tracker</title>
    {% endif %}
</head>
<body>
    <nav class="navbar">
      <div class="container">
        <div class="trade_tracker_logo" >
        <a class="navbar-link" href="/">Trade Tracker</a>
        </div>
        <div class="navbar-right">
            {% if current_user.is_authenticated %}
            <a class="navbar-link new_post" href="{{url_for('posts.new_post')}}">New Post</a>
            <a class="navbar-link" href="{{url_for('users.account')}}">Account</a>
            <a class="navbar-link" href="{{url_for('users.logout')}}">Logout</a>
            {% else %}
            <a class="navbar-link" href="{{url_for('users.login')}}">Login</a>
            <a class="navbar-link" href="{{url_for('users.register')}}">Register</a>
            {% endif %}
        </div>
      </div>
    </nav>     
      <main role="main" class="container">
        <div class="sidebar">
          <div class="top">
              <div class="logo">
                  <i  class='bx  bx-candles'></i>
                  <span>Trade Tracker</span>
              </div>
              <i class="bx bx-menu" id="btn"></i>
          </div>
          <div class="user"> 
            {% if current_user.is_authenticated %}
            <img src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}" class="user-img">
            <div>
                <p class="bold">{{ current_user.username }}</p>
            </div>
            {% endif %}            
          </div>
          <ul>
            {% if current_user.is_authenticated %}
              <li>
                  <a href="{{ url_for('users.portfolio', username=current_user.username) }}">
                    <i class='bx bx-pie-chart-alt' ></i>
                    <span class="nav-item">Portfolio</span>
                  </a>
                  <span class="tooltip">Portfolio</span>
              </li>
            {% endif %}
              <li>
                  <a href="{{ url_for('posts.news') }}">
                    <i class='bx bx-news'></i>
                    <span class="nav-item">News</span>
                  </a>
                  <span class="tooltip">News</span>
              </li>
              <li>
                  <a href="{{ url_for('posts.overview') }}">
                    <i class='bx bx-chalkboard' ></i>
                    <span class="nav-item">Overview</span>
                  </a>
                  <span class="tooltip">Overview</span>
              </li>
              <li>
                  <a href="{{ url_for('posts.earnings') }}">
                      <i class="bx bxs-food-menu"></i>
                      <span class="nav-item">Earnings</span>
                  </a>
                  <span class="tooltip">Earnings</span>
              </li>
      </div>
        <div class="alert">         
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert-{{ category }}" role="alert"  onload="slideAlert()">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <div class="blocks">
          <div class="block-content">
              {% block content %}{% endblock %}    
          </div>
          {% if show_secondary_block %}
          <div class="secondary-block-content">
            {% block secondcontent %}{% endblock %}
          </div>
          {% endif %}
        </div>
      </main>  
      <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>

tradetracker/templates/login.html
{% extends "layout.html" %} 
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group-elements">
                <legend class="form-head">Log In</legend>                
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}   
                    {{ form.email(class="form-control", placeholder="Enter Email") }}   
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}   
                    {{ form.password(class="form-control", placeholder="Enter Password") }}  
                </div>
                <div class="form-check">
                    <div class="form-check-elements">
                        {{ form.remember.label(class="form-check-label") }}  
                        {{ form.remember(class="form-check-input check") }}  
                    </div>
                </div>
            </fieldset>
            <div class="form-middle">
                <div class="form-group">
                    {{ form.submit(class="btn") }}
                </div>
                <small class="form-group">
                        <a href="{{ url_for('users.reset_request') }}" class="form-link">Forgot Password?</a>       
                </small>              
            </div>
            <div class="form-bottom">
                <small>
                    Need An Account? <a href="{{ url_for('users.register') }}" class="form-link">Sign Up Now</a>
                </small>
            </div>
        </form>
        
    </div>
{% endblock content %}

tradetracker/templates/portfolio.html
{% extends "layout.html" %}
{% set show_secondary_block = True %} 
{% block content %}
<div class="wrapper">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/2.2.0/chartjs-plugin-datalabels.min.js" 
    integrity="sha512-JPcRR8yFa8mmCsfrw4TNte1ZvF1e3+1SdGMslZvmrzDYxS69J7J49vkFL8u6u8PlPJK+H3voElBtUCzaXj+6ig==" 
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
    <div class="graph">  
        <h1>My Stocks and Shares!</h1>
        <canvas id="myChart" width="400" height="200"></canvas>
    </div>
    <script>
        Chart.register(ChartDataLabels);
        const ctx = document.getElementById('myChart');
      
        new Chart(ctx, {
          type: 'doughnut',
          data: {
            labels: {{ ticker_labels|tojson }},
            datasets: [{
              label: 'Number of shares',
              data: {{ ticker_amounts|tojson }},
            }]
            },
            options: {
                animation: {
                duration: 2000,
                easing: 'easeInOutQuart'
                },
                plugins: {
                    tooltip: {
                        enabled: false
                    },
                    datalabels: {
                        formatter: (value, context) => {
                            const totalShares = context.chart.data.datasets[0].data.reduce((acc, val) => acc + val);
                            const percentage = Math.round((value / totalShares) * 100);
                            return percentage + '%';
                        },
                        color: 'white',
                        font: {
                            size: 32,
                            weight: 'bold'
                        },
                    },
                    legend: {
                    position: 'bottom',
                    display: true,
                    labels: {
                        color: 'white',
                        font: {
                            size: 16,
                        }
                    }
                    },                   
                }
            }
        });
      </script>
    <div class="content-section portfolio-content">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="form-head">Update Your Portfolio!</legend>
                <div class="form-group">
                    {{ form.ticker.label(class="form-control-label") }}   
                    {{ form.ticker(class="form-control", placeholder="Enter Ticker") }}                      
                </div>
                <div class="form-group">
                    {{ form.amount.label(class="form-control-label") }}   
                    {{ form.amount(class="form-control", placeholder="Enter Amount") }}   
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn portfolio-btn") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block secondcontent %}
<div class="content-section">
    <div class="stock-elements">
        <div class="stock-overview">
            <h1>Stocks Overview</h1>
                <i class='bx bx-history history' id="click-history"></i>
            <h2>Total: {{ summary }} $</h2>
            <table class="stock-table">
                <thead>
                    <tr class="stock-tr">
                        <th>Ticker</th>
                        <th>Amount</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for index, row in df_overview.iterrows() %}
                    <tr class="stock-tr">
                        {% for value in row %}
                                <td>{{ value }}</td>
                        {% endfor %} 
                        <td>
                            <i class='bx bx-dollar' ></i>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="stock-history">
            <h1>Stocks history</h1>
                <i class='bx bx-dollar-circle history' id="click-overview"></i>
            <table class="stock-table">
                <thead>
                    <tr class="stock-tr">
                        <th>Ticker</th>
                        <th>Amount</th>
                        <th>Price</th>
                        <th>Total</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for index, row in df.iterrows() %}
                    <tr class="stock-tr">
                        {% for value in row %}
                        <td>{{ value }}</td>
                        {% endfor %}
                        <form action="{{ url_for('users.delete_stock', ticker_id = ticker_id[index]) }}" method="POST">
                            <td>
                                <button type="submit" class="delete-btn">
                                    <i class='bx bx-x delete-stock' id='{{ ticker_id[index] }}'></i>
                                </button>
                            </td>
                        </form>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
        const clickHistory = document.getElementById("click-history");
        var stockHistory = document.querySelector(".stock-history");
        var stockOverview = document.querySelector(".stock-overview");
        clickHistory.addEventListener("click", function() {
            stockOverview.style.display = 'none';
            stockHistory.style.display = 'block';
        })
        const clickOverview = document.getElementById("click-overview");
        clickOverview.addEventListener("click", function() {
            stockHistory.style.display = 'none';
            stockOverview.style.display = 'block';
        })

</script>

{% endblock %}
       